Refactor justfile and CI process (#36)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,41 +14,32 @@ defaults:
     shell: bash
 
 jobs:
-  ci:
-    name: CI
+  test:
+    name: Test
     runs-on: ubuntu-latest
     steps:
-      #############################################################
-      ## Full test
-      ##
       - uses: actions/checkout@v4
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
       - uses: taiki-e/install-action@v2
-        with: { tool: 'just,cargo-llvm-cov' }
+        with: { tool: just }
       - if: github.event_name == 'release'
         name: Ensure this crate has not yet been published (on release)
         run: just check-if-published
-      - run: RUST_BACKTRACE=1 just ci-test
+      - run: just ci-test
       - run: just ci-build-thumbv7em-none-eabi
       - name: Check semver
         uses: obi1kenobi/cargo-semver-checks-action@v2
-      #############################################################
-      ## Code coverage
-      ##
-      - if: github.event_name != 'release'
-        name: Generate code coverage
-        run: just ci-coverage
-      - if: github.event_name != 'release'
-        name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: target/llvm-cov/codecov.info
-          fail_ci_if_error: true
-      #############################################################
-      ## Test MSRV
-      ##
+
+  test-msrv:
+    name: Test MSRV
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
+        uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
       - name: Read MSRV
         id: msrv
         run: echo "value=$(just get-msrv)" >> $GITHUB_OUTPUT
@@ -57,11 +48,45 @@ jobs:
         with:
           toolchain: ${{ steps.msrv.outputs.value }}
       - run: just ci-test-msrv
-      #############################################################
-      ## Publish to crates.io
-      ##
-      - if: startsWith(github.ref, 'refs/tags/')
-        name: Publish to crates.io
+        env:
+          # Ignore warnings in MSRV. Sadly this cannot be done inside `just ci-test-msrv`
+          CI: ''
+
+  coverage:
+    name: Code Coverage
+    if: github.event_name != 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: 'just,cargo-llvm-cov' }
+      - name: Generate code coverage
+        run: just ci-coverage
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: target/llvm-cov/codecov.info
+          fail_ci_if_error: true
+
+  # This job checks if any of the previous jobs failed or were canceled.
+  # This approach also allows some jobs to be skipped if they are not needed.
+  ci-passed:
+    if: always()
+    needs: [ test, test-msrv, coverage ]
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
+
+  release:
+    if: startsWith(github.ref, 'refs/tags/')
+    needs: [ ci-passed ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Publish to crates.io
         run: cargo publish
         env:
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
